### ISSUE TITLE
Provide better way to override default Turtle panel

### ISSUE THREAD

**Issue by jamesrcounts** [TeachingKidsProgramming/TeachingKidsProgramming.Source.Java#13]
Because `getPanel` will create a new panel if the panel is null, the order of operations matters in some recipes.  In particular we have a [hint](https://github.com/TeachingKidsProgramming/TeachingKidsProgramming.Source.Java/blob/b1655b420110ea5343a527c2fcdac9fedebfef4b/src/org/teachingkidsprogramming/section07events/ManyAnimals.java#L23) in `ManyAnimals` indicating that turtles must be added to the `MultiTurtlePanel` before any other methods are called.  The `addTurtle` method will set the `MultiTurtlePanel` instance to be the `Turtle`'s panel, and this is how we get more than one turtle on a panel.  The hint is basically a workaround the default `Turtle` behavior, and it would be better to have a solution that did not require overtly hinting the students.

**Comment by lynnlangit** [comment]
refactored and lazyWindow object introduced
