### ISSUE TITLE
Need to Figure out what to do with TKP Worksheets

### ISSUE THREAD

**Issue by lynnlangit** [TeachingKidsProgramming/TeachingKidsProgramming.Source.Java#24]
Existing TKP Worksheets are no longer part of this build.  Need to revise, figure out / where how to publish.

Also explore the idea of TKPUnplugged activities in place or in addition to TKPJava Worksheets

Worksheets are currently here (only in src) - https://github.com/TeachingKidsProgramming/TeachingKidsProgramming.Source.Java/tree/master/src/main/resources/documents

**Comment by jamesrcounts** [comment]
I think this just fell through the cracks and we can probably replicate the old behavior.  I think some things were moved around into resource folders when we mavenized.  Putting them back where they were might be enough to get them back into the build... if that behavior is still what we want.  We are talking about the Word docs right?

**Comment by lynnlangit** [comment]
These are being edited and revised as part of the documentation re-write. The updated worksheets will be part of the documentation and NOT part of the GitHub download.  In the interim, we are leaving the current version of the worksheets in the source TKPJava repo -- https://github.com/TeachingKidsProgramming/TeachingKidsProgramming.Source.Java/tree/master/src/main/resources/documents
