### ISSUE TITLE
Codenvy Plugin - Run this Class

### ISSUE THREAD

**Issue by jamesrcounts** [TeachingKidsProgramming/TeachingKidsProgramming.Source.Java#37]
This plugin would allow students to run a specific recipe without editing the POM.  It would adjust the POM for them, then do a build/run.

A really cool UI for this would be to put the play button in the gutter next to the class declaration when a main method is detected.  

It should also be possible to replace the default play button in code envy, giving it the behavior we want.

Another alternative would be to show a modal dialog that listed all the classes with main methods, and the student could pick the one they want.

Some of these options are better than others.  All are better than editing the POM by hand.

**Comment by lynnlangit** [comment]
Codenvy was purchased by RedHat in 2017
