### ISSUE TITLE
Make solutions available for all courseware

### ISSUE THREAD

**Issue by jamesrcounts** [TeachingKidsProgramming/TeachingKidsProgramming.Source.Java#4]
The `org.teachingkidsprogramming.recipes.completed` package has solutions for quite a few (all?) recipes.  However solutions for quizzes and deep dives are harder to find (some might not exist at all, I'm not sure).  The harder to find solutions are in the test packages, so `SimpleSquareQuizTest` has a correct solution to `SimpleSquareQuiz` in the form of the nested class `SimpleSquareQuizTest.SimpleSquareCorrectQuiz`.  Teachers already have a hard time finding the `completed` package, and digging around in the tests is probably a non-starter for most teachers.

So, all the solutions should be together, and easy to find in the repository, and all courseware should have an example solution.  This will be one step in the right direction.  We should probably figure out a way to make it even easier on the teachers, but this will improve things.

**Comment by isidore** [comment]
Or we could just turn off that warning in eclipse.

**Comment by lynnlangit** [comment]
completed in folders under /completed
