### ISSUE TITLE
Should this answer be here?

### ISSUE THREAD

**Issue by jamesrcounts** [TeachingKidsProgramming/TeachingKidsProgramming.Source.Java#6]
One of these things is not like the others, in `DeepDive04Mastery.dividing()`, the answer `.2` is given in the second assert, instead of a blank.  In its siblings `dividingIntegers`, `convertingToText`, etc, blanks are used in the second assert.

See [here](https://github.com/TeachingKidsProgramming/TeachingKidsProgramming.Source.Java/blob/b1655b420110ea5343a527c2fcdac9fedebfef4b/src/org/teachingkidsprogramming/section04mastery/DeepDive04Mastery.java#L117)

**Comment by lynnlangit** [comment]
fixed
