### ISSUE TITLE
New Virtual Proctor sometimes returns Status 411

### ISSUE THREAD

**Issue by jamesrcounts** [TeachingKidsProgramming/TeachingKidsProgramming.Source.Java#60]
![screen shot 2015-05-21 at 11 07 39 am](https://cloud.githubusercontent.com/assets/1542583/7757138/e89d0570-ffb4-11e4-8277-8e71e9c2f122.png)

Via Gen:
On two postings.
One where I had no class name, the second once i added class name. (Same error both times)

**Comment by jamesrcounts** [comment]
So far... unable to reproduce.

**Comment by lynnlangit** [comment]
new Virtual Proctor deployed
