### ISSUE TITLE
Update implementation of setting the background window color of the main TKPJava window

### ISSUE THREAD

**Issue by lynnlangit** [TeachingKidsProgramming/TeachingKidsProgramming.Source.Java#81]
Current method is 'clunky'

Tortoise.getBackgroundWindow( ).setBackground(PenColors.Grays.Silver);

should be something like this:

Tortoise.setBackgroundWindowColor(PenColors.Grays.Silver);

**Comment by isidore** [comment]
it's not clunky, it's good encapsulation. pushing it to the Tortoise creates a god object, reduces access to the rest of the background windows, doesn't teach about returning objects or trains (both important oo concepts). 
Worse, it trains kids on bad object design, when we should be endeavoring to show them the best of object design.
