### ISSUE TITLE
TKP_launcher.jar doesn't work for folder names with spaces and returns no error message

### ISSUE THREAD

**Issue by lynnlangit** [TeachingKidsProgramming/TeachingKidsProgramming.Source.Java#9]
Add a validation to check for folder names with spaces.  Replace spaces with a character, so that the launcher will function as expected even if the user unzips to a folder they create which has a folder name with spaces in it, i.e. 'TKP Source'

**Comment by jamesrcounts** [comment]
Tested. Works now.
